select Onum,Amt,Odate from Orders;
select * from Customers where Snum=1001;
select city,Sname,Snum,Comm from Salepeople;
select * from Customers order by Cname;
select * from Customers order by City;
select * from Orders where Odate between '1990-10-04' AND '1990-10-08';
select salary,empName,city from employee order by salary desc;
select salary,empName,city from employee order by city desc,empName desc;
select * from Customers order by Cname;
select count(*) from employee where city='Yangon';
select count(empName) 'Total',max(salary) from employee where city='Yangon';
select count(empName) 'Total',max(salary),min(salary) from employee where city='Yangon';
select salary,empName from employee where city='Yangon';
select count(empName) 'Total',max(salary),min(salary) from employee where city='Mandalay';
select sum(salary) 'Total salary for Yangon' ,avg(salary)'Avg Salary' from employee where city='Yangon';
select sum(salary) 'Total salary for Yangon' ,avg(salary)'Avg Salary' from employee where city='Mandalay';
select ucase(empName),lcase(city) from employee;
select city,sum(salary) 'Total Salary' from employee group by city;
select department, sum(salary) 'Total Salary',count(*)'No.Employee' from employee group by department;
select department,sum(salary) 'Total Salary',round(avg(salary))'Avg Salary',count(*)'No.Employee' from employee group by department;
select city,round(avg(salary)) 'Avg Salary' from employee group by city having round(avg(salary))>=9000;
select * from Salepeople;
select Sname,City from Salepeople where City='Landon' AND Comm>0.10;
select * from Customers where Cname LIKE 'C%';
select * from Customers where Snum IN(1001,1002,1007);
select * from Salepeople where Comm NOT IN(0.10,0.13,0.15);
select DISTINCT(City) from Customers;
select * from Customers LIMIT 3;
select * from Customers order by Rating desc LIMIT 3;
select * from Salepeople where city='Rome';
