select name,city from users;
select * from users LIMIT 3;
select city from users;
select distinct city from users;
select * from users where city='Yangon';
select * from users where city !='Yangon';
select * from users where city='Mandalay';
select * from users where id>=3;
select * from users where id between 2 AND 4;
select empName,jobPosition,salary from employee where salary>=6000;
select empName,jobPosition,salary from employee where salary between 6000 AND 9000;
select empName,jobPosition,salary from employee where salary IN(6000,7000,9000);
select empName,jobPosition,salary from employee where empName LIKE '%ook';
select empName,jobPosition,salary from employee where empName LIKE 'J%';
select * from employee;
select empName,jobPosition,salary from employee where salary not between 6000 AND 9000;
select empName,jobPosition,salary from employee where empName NOT LIKE '%ng';
select * from employee where salary>=8000 AND city='Yangon';
select * from employee where salary>=8000 OR city='Yangon';
select * from employee where dob>='1994-8-01' AND (city='Mandalay' OR city='Yangon');
select * from employee where dob>='1994-8-01' OR city IN('Yangon','Mandalay');
select * from employee where dob>='1994-8-01' AND city IN('Yangon','Mandalay');